name: hop
version: 0.20.0-beta
author: Kevin Moore <kevin@thinkpixellab.com>
description: A task management framework for Dart
homepage: https://github.com/kevmoo/hop.dart
documentation: http://kevmoo.github.io/hop.dart
environment:
  sdk: '>=0.4.5+1.r21094'
dependencies:
  unittest: '>=0.4.5+1'
  bot: '>=0.16.3'
  args: '>=0.4.5+1'
  logging: '>=0.4.5+1'
  pathos: '>=0.4.5+1'
  meta: '>=0.4.5+1'
dev_dependencies:
  html5lib: '>=0.4.1'
