name: hop
version: 0.20.0+1
author: Kevin Moore <kevin@thinkpixellab.com>
description: Dart Task Framework
homepage: https://github.com/kevmoo/hop.dart
documentation: http://kevmoo.github.io/hop.dart
environment:
  sdk: '>=0.4.5+1.r21094'
dependencies:
  unittest: '>=0.4.5+1'
  args: '>=0.4.5+1'
  bot: '>=0.16.3'
  logging: '>=0.4.5+1'
  bot_io: '>=0.20.0-dev'
  pathos: '>=0.4.5+1'
  meta: '>=0.4.5+1'
dev_dependencies:
  html5lib: '>=0.4.2'
